#
# eduroam Provisioning Tools
#  Common configuration file for Wi-Fi profile provisioning scripts
#  Target: All OS
# 
# Usage:
#  - Put this file into a protected director on a web server.
#    Make sure the directory is not accesible from outside.
#
# 20260715 Hideaki Goto (Tohoku University and eduroam JP)
#	New configuration file in .ini format.
# 20260716 Hideaki Goto (Tohoku University and eduroam JP)
#	Ease configuration (Windows). Fix Passpoint.
#

[default]
#
# General
#

# Base file name of the profile for download.
# (no space)
#FileName=passpoint
FileName=eduroam

# Expiration or removal date.  (effective only on some systems)
# It is recommended to set this in order to reduce unnecessary traffic.
ExpirationDate=
#ExpirationDate=2023-01-05T00:00:00Z


#
# Passpoint (ANQP)
#

# Enable (1) or disable (0) Passpoint
Passpoint=0

# Home Domain Name helps user devices distinguish home/foreign ANP.
# (You may simply use your own DNS domainname if no such control is used.)
HomeDomain=example.ac.jp

# Friendly Name is displayed on user devices.
friendlyName=eduroam (Example Univ.)

# Roaming Consortium Organization Identifiers
# (comma-separated, no space)
# Note: If an RCOI is set, Windows does not provide SSID-based connection.
#RCOI=001bc50460,5a03ba0000,5a03ba0800
#RCOI=001bc50460
RCOI=

# NAI realm is used for network selection using ANQP.
NAIrealm=example.ac.jp

# SSID (may not be blank)
#SSID=_Passpoint
SSID=eduroam


#
# Server authentication
#

# Domain name embedded in the server cert.
AAAFQDN=idp.example.ac.jp

# CA certificate
# (contains only one CA cert., must be in PEM format)
CAfile=../etc/isrgrootx1.pem

# Intermediate CA certificates to be embedded additionally in the profile.
# (must be in PEM format)
ICAfile=

# Name of Intermediate CA certificate
# (Apple only)
ICAcertname=Intermediate CA cert.

# SHA-1 fingerprint of the Trusted Root CA certificate
# (Windows only)
# $ openssl x509 -fingerprint -noout -in rootCAfile.pem
TrustedRootCAHash=CA:BD:2A:79:A1:07:6A:31:F2:1D:25:36:35:CB:03:9D:43:29:A5:E8

#
# Profile signing
#
signercert=../etc/cert.pem
signerchain=../etc/chain.pem
signerkey=../etc/privkey.pem

# (Windows only)
# RSA certificate for signing is required. ECDSA one does not work.
# Windows 10 and 11 21H2 require an EV certificate for signing.
# xmlsec1 command requires certificates packed in .pfx format.
# All certificates will be embedded in the profile.
# To create a .pfx file, 
#  $ openssl pkcs12 -export -in all-certs.pem \
#     -inkey privkey.pem -out signercert.pfx
signercertpfx=../etc/signercert.pfx
pfxpasswd=
#
# Additional (I)CA certificates to embed. (optional)
CAfile_win=
#CAfile_win=../etc/ica.pem


#
# Miscellaneous
#

# (Apple only)
# Apple Payload configuration
PayloadDisplayName=eduroam (Example Univ.)
description=Configure eduroam for Example Univ.
#
# (Set a globally-unique, fixed UUID for the same kind of profile.)
# (Please use YOUR OWN UUID.)
PLuuid=873d2e56-473b-836a-d718-d362e340c146
PLID=ExampleUniv.873d2e56-473b-836a-d718-d362e340c146

# (Windows only)
# Carrier ID (Set a globally-unique UUID for the operator.)
# (You may leave it as it is if you don't have one.)
CarrierId=5ca9e3f8-e7a4-d0d7-562a-9f9da6d5e412
# Subscriber ID
SubscriberId=1234567890

# Secret key for win-helper.cgi
# Make sure to use a UNIQUE random string for YOUR OWN SITE.
HelperSecret=4BQkGpgtc217OleZt7Gs9rSaVz7H0yDy

